I2C_ENABLE = yes
I2C_DRIVER_REQUIRED = yes
BOOTMAGIC_ENABLE = no
ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes
VIA_ENABLE = yes
CONSOLE_ENABLE = no
RGBLIGHT_ENABLE = yes
RGBLIGHT_DRIVER = ws2812

POINTING_DEVICE_DRIVER = custom
POINTING_DEVICE_ENABLE = yes