// Copyright 2025 Morgan Newell Sun (@eynsai)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#define DYNAMIC_KEYMAP_LAYER_COUNT 8
#define VIA_EEPROM_CUSTOM_CONFIG_SIZE 256

#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_CHRISTMAS
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_RGB_TEST
#define RGBLIGHT_EFFECT_TWINKLE

#define KNOB_VIA_DEFAULT_SENS_0 5
#define KNOB_VIA_DEFAULT_HUE_0 0
#define KNOB_VIA_DEFAULT_SAT_0 255

#define KNOB_VIA_DEFAULT_SENS_1 5
#define KNOB_VIA_DEFAULT_HUE_1 0
#define KNOB_VIA_DEFAULT_SAT_1 0